### ISSUE TITLE
Possible to use as autocomplete?

### ISSUE THREAD

**Issue by jsieler** [dons20/UIKit-VSCode#10]
First of all, thanks for really nice extension!

Just only one question, is it possible to use it not only as snippets, but as autocomplete feature?

Thanks!

**Comment by dons20** [comment]
Hi @jsieler 

Thanks for the kind words! The way that snippets work within VSCode allows it to utilize the autocomplete feature by default. If you do not have autocomplete or tab completion enabled, please check your user settings in VSCode (Hit F1 and type User Settings and choose the first result). Ensure that snippet auto-completion is enabled. 

Let me know if you have any additional queries.

**Comment by jsieler** [comment]
Thanks for your reply!

The autocomplete works not the way i probably want... When i start writing "uk-" and press "CTRL+SPACE" it display whole list of suggestions. So far it's okay.

But, if i choose one and press "ENTER" it inserts the whole snippet, instead of class name only.

You know what i mean?

**Comment by dons20** [comment]
Oh I get what you're saying. I'm going to look into it and see if there's a setting for that, otherwise I'll just have to add in a few extra snippets.

**Comment by jsieler** [comment]
Still no news about?

**Comment by dons20** [comment]
Sorry I've been a little busy since then. But here's an update for you regarding this issue.

Most of the snippets have a class-only or attribute-only version which is normally the `uk-item` (where item is the name of the particular component). The more complex versions of that snippet are the ones that insert the entire snippet. 

As example, `uk-accordion` inserts 

```html
uk-accordion
```
while `uk-accordion-sample` inserts

```html
<ul uk-accordion>
    <li>
        <h3 class="uk-accordion-title"></h3>
        <div class="uk-accordion-content">
            
        </div>
    </li>
</ul>
```

Now if there's a particular snippet you'd like to see extended to have a particular syntax, let me know. So far it doesn't seem that VSCode allows you to just insert class names only. That's how snippets work though. They insert a predefined string which means that it's something I would have to manually add.

Let me know if you have any further questions.

**Comment by kovalchyk** [comment]
Hi! is the current version of uikit 3? at times there is syntax version 2 (for example uk-icon)

**Comment by dons20** [comment]
@kovalchyk Yes, this is uikit version 3. I haven't updated it in a while, but the current snippets are indeed from uikit beta 30. Will release an update for beta 42 in the coming days.

**Comment by kovalchyk** [comment]
It would be great! Thanks for your work!

**Comment by kovalchyk** [comment]
@dons20 It would be great! Thanks for your work!
