### ISSUE TITLE
autocomplete works everywhere

### ISSUE THREAD

**Issue by alpap** [dons20/UIKit-VSCode#17]
- [x] Check that you are running the latest version of Visual Studio Code
- [x] Check that you are running the latest version of the snippet plugin (UIkit 3.0 Snippets 1.4.0)
- [x] Check that the extension is enabled
- [x] Check that your editor suggestions are enabled (or manually trigger them with <kbd>Ctrl</kbd> + <kbd>Space</kbd>

### Problem Encountered

auto completion works everywhere not just in specific files

### Steps to Reproduce

1. Step 1 ...
2. Step 2 ...

**Comment by dons20** [comment]
Hi @alpap,

This was enabled by default in [1.4.0](https://github.com/dons20/UIKit-VSCode/blob/master/CHANGELOG.md#version-140-november-3-2018) because of the growing list of file extensions that had to be added manually for the plugin to work in. 

Here are some steps which might help you:

1. **Language specific settings** - You can change editor settings per file type in VSCode. As an example, to disable snippet suggestions in a particular filetype: [Official Docs](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings)

    Press F1 ➡Preferences: Configure Language Specific Settings
    ```json
    "[filetype]": {
      "editor.snippetSuggestions": "none"
    }
    ```

2. **Disable the extension in your workspace**

3. **Modify Quick Suggestions** 

    ```
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
      }
    ```

Hopefully these suggestions can help you. There are no plans to revert the plugin to its prior functionality due to the reasons mentioned. Feel free to re-open if you have any further questions.
