### ISSUE TITLE
Some suggestions work, others don't

### ISSUE THREAD

**Issue by Hachann** [dons20/UIKit-VSCode#5]
Hello,

First, thank you very much for this wonderful tool !

These suggestions work fine when I press Enter after the suggestion has been chosen : 
`uk-$`
`uk-article-sample`

The code is perfect.

But, using the same process with (for exemple) : 
`uk-section`

All I get in writing is : 
`class="uk-section uk-section-default"`

No other text is printed on screen : no `<div>` etc.

Can you help me ?

Thanks alot !

**Comment by dons20** [comment]
Hi,
Thanks for using my snippet extension! 
Now as for your problem, the last update was version 1.1.0, which made it so that the class-only version of each snippet would be uk-{item} (where {item} is the name of the snippet category). The extended version for most of the snippets is `uk-{item}-default` or `uk-{item}-sample`.

For example, `uk-section` will insert 
```html 
class="uk-section uk-section-default"
```
 while `uk-section-default` will insert 
```html 
<div class=\"uk-section uk-section-default\">

</div>
```

Of course, it varies per snippet category, but the general rule is that the class-only version is the basic snippet, while the extended one will usually end with `sample` or `default`.

**Comment by Hachann** [comment]
Thank you, it works like a charm ! I'm glad you took some time to explain !
